name: NPM Publish

on:
  push:
    tags:
      - v*

jobs:
  Publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # Adapt the version to the minimal required
          node-version: 14

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Publish on NPM
        run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.npm_token}}
